import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "../components/Home/NavBar"
import SideBar from "@/components/Home/SideBar";
import Footer from "@/components/Home/Footer";
import Profile from "@/components/Profile/Profile";
import Header from "@/components/Home/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body  className={`min-h-screen  ${inter.className}`} >{children}

      <NavBar />
      <div className="flex">
         <SideBar />
         <Header />
      </div>
      <Footer />
      </body>
    </html>
  );
}
